# Generated by Django 2.2.20 on 2021-04-25 17:28

from django.db import migrations


def flat_owner_relation(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for connect in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            owner=connect.owner,
            phone_number=connect.owners_phonenumber,
            clear_phone_number=connect.owners_pure_phone
        )
        connect.owners.set([owner])

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210425_1714'),
    ]

    operations = [migrations.RunPython(flat_owner_relation)
    ]
